sylabs/singularity-admindocs

installation.rst

This fixes an invalid path for cloned directory

Update cloning instructions

---

configfiles.rst
installation.rst

Document external binary finding changes

---

configfiles.rst

Add note r.e. restricting container types when using ECL

---

installation.rst

Document relocatable installation

---

configfiles.rst
security.rst

Update cgroups information for v2 support

---

configfiles.rst

Document `--insecure` for global remote endpoints

---

configfiles.rst

Add nvidia-container-cli functionality notes

---

admin_quickstart.rst

added space, now it looks better.

minor fix in link in docs 

---

admin_quickstart.rst

Update quickstart for 3.10 deps, conmon etc.

---

installation.rst

Update Go version info / deps also.
Fixes #44

Add conmon / runc to installation docs

---

security.rst

Add unpriv cgroups notes to security.rst

---

configfiles.rst

* New `singularity.conf` options.
* New cgroups functionality (unpriv, unified v2)
Fixes #47

Update configfiles.rst for 3.10

---

user_namespace.rst

Add --sif-fuse to user_namespace.rst

---

.circleci/config.yml
_templates/layout.html

add 3.9 old version notice

---

.circleci/config.yml
_templates/layout.html

add 3.8 old version notice

---

installation_environments.rst

Fix URL to the Sherlock cluster website

Fix URL to the Sherlock cluster website

---

configfiles.rst

Update sessiondir max size comment

---

installation.rst

Document runc/crun, proot dependencies

---

LICENSE
conf.py
installation.rst

Document mconfig --reproducible flag

---

installation.rst

document PanFS limitations

---

admin_quickstart.rst
configfiles.rst
installation.rst
security.rst
user_namespace.rst

* Mention proot, OCI functionality.
* Tweak explanation of implications of unprivileged install / userns.
* Highlight effect on security restrictions of unprivileged install.

3.11 Larger Edits

---

configfiles.rst

Update the documentation to reflect behavior in OCI-mode.
This duplicates quite a lot of text from the user guide. I feel this is warranted so that the complete behaviour is visible to the admin, without having to go between user and admin guides.
Fixes #106

configfiles: Update capabilities docs for OCI-mode

---

admin_quickstart.rst
installation.rst

Update requirements for OCI-mode

---

admin_quickstart.rst
security.rst

Rework security overview to include OCI-Mode

---

installation.rst

Document kernel vs fuse overlay circumstances

---

installation.rst

Document OCI-mode limitations across common distros

---

admin_quickstart.rst

Add backward/forward compatibility notes

---

configfiles.rst
index.rst
installation.rst
new.rst

Add new in 4.0 page

---

.circleci/config.yml
conf.py
replacements.py

Update config and replacements for 4.0.0 release.

chore: 4.0.0 release

---

.circleci/config.yml

Update CircleCI versions of: node (20-slim) and python (3.12).

update CircleCI versions of node, python

---

.circleci/config.yml

Pick #127 
Update CircleCI versions of: node (20-slim) and python (3.12).

update CircleCI versions of node, python (4.0)

---

installation.rst

Add Dockerfile build distro limitations

---

admin_quickstart.rst

Mention multi-layer OCI-SIF compatibility

---

LICENSE
conf.py
index.rst
new.rst

What's new in 4.1 content

---

appendix.rst

Update appendix file list

---

configfiles.rst

singularity.conf option: allow uts ns

---

configfiles.rst

singularity.conf: "add user ns" option

---

admin_quickstart.rst
installation.rst
user_namespace.rst

EL7 is EOL - drop installation and limitations content.

Drop EL7 content

---

admin_quickstart.rst
installation.rst
user_namespace.rst

EL7 is EOL - drop installation and limitations content.

Drop EL7 content (4.1)

---

admin_quickstart.rst
installation.rst

Update quickstart / install sections for 4.3

---

admin_quickstart.rst

Mention cosign signature compatibility

---

user_namespace.rst

Document libsubid implications
